#!/bin/sh

# github profile repo
echo "start profile---------"
echo "start profile---------"

mkdir profile
cp README.md ./profile/README.md
cp avatar.png ./profile/avatar.png
cd profile
git init
git config  user.email "827094438@qq.com"
git config  user.name "bigAken"
ls
git add .
git commit -m '发版'
git remote add origin git@github.com:bigAken/bigAken.git
git push -f origin master
cd ..
rm -rf profile 
echo "end profile--------"
echo "end profile--------"

# 发版
npm run build
git  add .
git commit -m 'blog'